# Generated by Django 3.2.6 on 2021-08-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static/default.jpg', upload_to='Profile Pics'),
        ),
    ]
